Connectify/urls.py
"""Defines URL patterns for Connectify."""
from django.urls import path, include
from .import views



app_name = 'Connectify'
urlpatterns = [   

    
    path('', views.index, name='index'), #home page
    path('category/', views.categories, name='category'), 
    path('category/<int:category_id>/', views.category_products, name='category_products'),
    path('<int:id>/',views.detail,name='detail'),#show  detail of a single product
    
    path('', include('django.contrib.auth.urls')),
    path('user_logout/',views.user_logout,name= "logout"),
    path('register/', views.register_user, name='register'),
    path('login/', views.login_user, name='login'),
    path('about/', views.about_us, name='about_us'),  # URL for the about us page
   
    
    path('checkout/', views.checkout, name='checkout'),
    path('payments/', views.payment_process, name='payment_process'),
    path('payments/success/', views.payment_success, name='payment_success'),
    
    
   # path('addresses/<int:address_id>/delete/', views.address_delete, name='address_delete'),
    path('cart_summary/', views.cart_summary, name='cart_summary'),
    path('view_businesses/<int:product_id>/', views.view_businesses, name='view_businesses'),
   

    ]

Group1/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings




urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('Connectify.urls', namespace='Connectify')), 
    path('Registerbusiness/', include('Registerbusiness.urls', namespace='Registerbusiness')),  
    path('api/',include('api.urls'))
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    

Registerbusiness/urls.py
from django.urls import path
from . import views

app_name = 'Registerbusiness'
urlpatterns = [

    path('', views.dashboard, name='dashboard'),
    path('register/', views.register_business, name='register_business'),
    path('user_logout/',views.user_logout,name= "logout"),
    path('login/', views.business_owner_login, name='business_owner_login'),
    path('products/add/', views.add_product, name='add_product'),
    path('business_home/',views.business_home, name = 'business_home'),
   
]

api/urls.py
from django.urls import path, include
from. import views
from rest_framework.routers import DefaultRouter

router = DefaultRouter()

router.register("products", views.ProductsViewSet)
router.register("categories", views.CategoriesViewSet)

urlpatterns = [
    path("", include(router.urls)),
    # path('products',views.api_products),
    # path('products',views.ApiProducts.as_view()),
    # path('categories',views.ApiCategories.as_view()),
    # path('product/<str:pk>',views.ApiProduct.as_view()),
    # path('category/<str:pk>',views.ApiCategory.as_view()),
]

Registerbusiness/models.py
from django.db import models
from Connectify.models import Category




class BusinessOwner(models.Model):
  
    name = models.CharField(max_length=255)
    description = models.TextField()
    contact_email = models.EmailField()
    contact_phone = models.CharField(max_length=20)
    contact_info = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    
    
    def __str__(self):
        return self.name
        




class Product(models.Model):
    owner = models.ForeignKey(BusinessOwner, on_delete=models.CASCADE, related_name='business_products')
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='product_images/')
    inventory_count = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    
    def __str__(self):
        return self.name

Registerbusiness/forms.py
from django import forms
from Connectify.models import Category
from .models import BusinessOwner,Product
from django.contrib.auth import authenticate

class BusinessSignUpForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)  # Add password field explicitly

    class Meta:
        model = BusinessOwner
        fields = ['name', 'description', 'contact_info', 'contact_email', 'contact_phone', 'password']


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['owner', 'name', 'description', 'price', 'image', 'inventory_count', 'category']

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.fields['category'].queryset = Category.objects.all()  # Populate category choices
        
class BusinessLogInForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            if user is None or not user.is_active:
                raise forms.ValidationError("Invalid username or password.")

        return cleaned_data

Registerbusiness/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login,logout
from django.contrib import messages
from django.urls import reverse
from .models import BusinessOwner,Product
from django.contrib.auth.decorators import login_required
from .forms import ProductForm, BusinessSignUpForm,BusinessLogInForm


def register_business(request):
    if request.method == 'POST':
        form = BusinessSignUpForm(request.POST)
        if form.is_valid():
            form.save()
            # Redirect to a success page or home page
            return redirect('Registerbusiness:dashboard')
    else:
        form = BusinessSignUpForm()
    return render(request, 'Registerbusiness/business_owner_register.html', {'form': form})

def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        
        if form.is_valid():
            product = form.save(commit=False)
            
            # Check if the owner is provided in the form data
            owner_name = form.cleaned_data.get('owner_name')
            if owner_name:
                # If the owner's name is provided, create a new BusinessOwner instance
                owner = BusinessOwner.objects.create(name=owner_name)
                product.owner = owner
            else:
                # If no owner's name is provided, set a default owner or handle as needed
                # Example: Assuming there's a default owner named "Default Owner"
                default_owner = BusinessOwner.objects.get_or_create(name='Default Owner')[0]
                product.owner = default_owner
            
            
            # Check if the owner is provided in the form data
            owner_name = form.cleaned_data.get('owner_name')
            if owner_name:
                # If the owner's name is provided, create a new BusinessOwner instance
                owner = BusinessOwner.objects.create(name=owner_name)
                product.owner = owner
            else:
                # If no owner's name is provided, set a default owner or handle as needed
                # Example: Assuming there's a default owner named "Default Owner"
                default_owner = BusinessOwner.objects.get_or_create(name='Default Owner')[0]
                product.owner = default_owner
            
            product.save()
            return redirect('Registerbusiness:dashboard')
            
    else:
        form = ProductForm()
    return render(request, 'Registerbusiness/add_product.html', {'form': form})
    






def dashboard(request):
    # Add logic to fetch data for the dashboard if needed
    return render(request, 'Registerbusiness/dashboard.html')

def user_logout(request):
  logout(request)
  #redirect to the default home page
  return redirect('Registerbusiness:dashboard')


def business_owner_login(request):
    if request.method == 'POST':
        form = BusinessLogInForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                # Redirect to dashboard or another page after successful login
                return redirect('Registerbusiness:dashboard')  # Replace 'dashboard' with your dashboard URL name
            else:
                messages.error(request, 'Invalid username or password.')
    else:
        form = BusinessLogInForm()
    return render(request, 'Registerbusiness/business_owner_login.html', {'form': form})

def business_home(request):
    return render(request, 'Registerbusiness/business_home.html',{})

Registerbusiness/templates/Registerbusiness/add_product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'Connectify/style.css' %}">
    <title>Document</title>
</head>
<body>
    
<div class="product">
    {% block title %}Add Product{% endblock %}

    {% block content %}
        <h1>Add a New Product</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="file" name="image">
            <button type="submit">Add Product</button>
        </form>
    {% endblock %}
    
</div>
<script>
    // Array of background image URLs
    var backgroundImageUrls = [
        "https://img.freepik.com/premium-photo/shopping-bags-brown-background_934652-2196.jpg",
        "https://as2.ftcdn.net/v2/jpg/03/12/43/13/1000_F_312431352_FCkZ5r0gRzUcS7GyvsRtnxECfXv6EKsJ.jpg",
        "https://png.pngtree.com/background/20230819/original/pngtree-eco-friendly-brown-shopping-bags-with-leaf-shadow-on-green-background-picture-image_4735897.jpg"
        // Add more image URLs as needed
    ];

    var currentImageIndex = 0; // Index of the currently displayed image

    // Function to change the background image
    function changeBackgroundImage() {
        // Increment the current image index
        currentImageIndex = (currentImageIndex + 1) % backgroundImageUrls.length;

        // Get the body element
        var body = document.body;

        // Change the background image
        body.style.backgroundImage = "url('" + backgroundImageUrls[currentImageIndex] + "')";

        // Call the function recursively after a certain interval (e.g., every 10 seconds)
        setTimeout(changeBackgroundImage, 10000); // Change image every 10 seconds (10000 milliseconds)
    }

    // Call the changeBackgroundImage function to start changing the background
    changeBackgroundImage();
</script>
<footer class="py-5 bg-success" style="background-color: #033d24;">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-6 col-sm-12 mb-4 mb-lg-0">
                <div class="hours">
                    <h3><b>OFFICE HOURS</b></h3>
                    <pre class="try">   
                        <b>MONDAY: 7am-11pm</b>
                        <b>TUESDAY: 7am-11pm</b>
                        <b>WEDNESDAY: 7am-11pm</b>
                        <b>THURSDAY: 7am-11pm</b>
                        <b>FRIDAY: 7am-11pm</b>
                        <b>SATURDAY: 7am-8pm</b>
                        <b>SUNDAY: 7am-7pm</b>
                    </pre>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 mb-4 mb-lg-0">
                <div class="location">
                    <h3><b>LOCATION</b></h3>
                    <pre class="try">
                        <b>KAMPALA UGANDA</b>
                        <b>BUILDING: HAM TOWERS</b>
                        <b>ROOM NUMBER: R45</b>
                        <b>MAKERERE HILL ROAD, KAMPALA</b>
                    </pre>
                </div>
            </div>
            <div class="col-lg-4 col-md-12 col-sm-12 mb-4 mb-lg-0">
                <div class="menu">
                    <h3><b>MENU</b></h3>
                    <a class="nav-link active" aria-current="page" href="{% url 'Connectify:index' %}"><b>HOME</b></a>
                    <a class="nav-link" href="{% url 'Connectify:logout' %}"><b>LOGOUT</b></a>
                    <a class="nav-link" href="{% url 'Connectify:login' %}"><b>LOGIN</b></a>
                    <a class="nav-link" href="{% url 'Connectify:register' %}"><b>SIGNUP</b></a>
                    <a class="nav-link" href="{% url 'Connectify:about_us' %}"><b>ABOUT US</b></a>
                    <a href="{% url 'Connectify:category' %}" class="nav-link"><b>CATEGORIES</b></a>
                    
                </div>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="contact text-center">
                    <h3><b>CONTACT US</b></h3>
                    <b><img src="https://i.pinimg.com/originals/84/4e/8c/844e8cd4ab26c82286238471f0e5a901.png" width="30px" height="30px"> PHONE NUMBER: +256773820218</b><br>
                    <b><img src="https://cdn4.iconfinder.com/data/icons/social-media-logos-6/512/112-gmail_email_mail-512.png" width="30px" height="30px"> EMAIL: connectifybusinessplatform@gmail.com</b><br>
                    <b><img src="https://pngimg.com/d/facebook_logos_PNG19750.png" width="30px" height="30px"> connectify</b><br>
                    <b><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Instagram_icon.png/2048px-Instagram_icon.png" width="30px" height="30px"> connectify</b><br>
                    <b><img src="https://www.edigitalagency.com.au/wp-content/uploads/new-Twitter-logo-x-black-png.png" width="30px" height="30px"> @connectify</b><br>
                    <b><img src="https://static.vecteezy.com/system/resources/previews/018/930/463/original/tiktok-logo-tikok-icon-transparent-tikok-app-logo-free-png.png" width="30px" height="30px"> @connectify</b><br>
                    <b><img src="https://png.pngtree.com/png-clipart/20221019/original/pngtree-whatsapp-icon-png-image_8704827.png" width="30px" height="30px"> +256704499826</b>
                </div>
            </div>
        </div>
    </div>
</footer>
</html>

Registerbusiness/templates/Registerbusiness/business_owner_login.html
<!-- business_owner_login.html -->

<!-- login.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'Connectify/style.css' %}">
    <title>Document</title>
</head>
<body>
   <div class="login" >
    

    {% block content %}
        <h1 style="color: white;"><b>Business Owner Login</b></h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="log">Login</button>
        </form>
    {% endblock %}
    
    
   </div> 
</body>
<script>
    // Array of background image URLs
    var backgroundImageUrls = [
        "https://img.freepik.com/premium-photo/shopping-bags-brown-background_934652-2196.jpg",
        "https://as2.ftcdn.net/v2/jpg/03/12/43/13/1000_F_312431352_FCkZ5r0gRzUcS7GyvsRtnxECfXv6EKsJ.jpg",
        "https://png.pngtree.com/background/20230819/original/pngtree-eco-friendly-brown-shopping-bags-with-leaf-shadow-on-green-background-picture-image_4735897.jpg"
        // Add more image URLs as needed
    ];

    var currentImageIndex = 0; // Index of the currently displayed image

    // Function to change the background image
    function changeBackgroundImage() {
        // Increment the current image index
        currentImageIndex = (currentImageIndex + 1) % backgroundImageUrls.length;

        // Get the body element
        var body = document.body;

        // Change the background image
        body.style.backgroundImage = "url('" + backgroundImageUrls[currentImageIndex] + "')";

        // Call the function recursively after a certain interval (e.g., every 10 seconds)
        setTimeout(changeBackgroundImage, 10000); // Change image every 10 seconds (10000 milliseconds)
    }

    // Call the changeBackgroundImage function to start changing the background
    changeBackgroundImage();
</script>
<footer class="py-5 bg-success" style="background-color: #033d24;">
    <div class="container">
       
            <div class="col-lg-4 col-md-6 col-sm-12 mb-4 mb-lg-0">
                <div class="location">
                    <h3><b>LOCATION</b></h3>
                    <pre class="try">
                        <b>KAMPALA UGANDA</b>
                        <b>BUILDING: HAM TOWERS</b>
                        <b>ROOM NUMBER: R45</b>
                        <b>MAKERERE HILL ROAD, KAMPALA</b>
                    </pre>
                </div>
            </div>
            <div class="col-lg-4 col-md-12 col-sm-12 mb-4 mb-lg-0">
                <div class="menu">
                    <h3><b>MENU</b></h3>
                    <a class="nav-link active" aria-current="page" href="{% url 'Connectify:index' %}"><b>HOME</b></a>
                    <a class="nav-link" href="{% url 'Connectify:logout' %}"><b>LOGOUT</b></a>
                    <a class="nav-link" href="{% url 'Connectify:login' %}"><b>LOGIN</b></a>
                    <a class="nav-link" href="{% url 'Connectify:register' %}"><b>SIGNUP</b></a>
                    <a class="nav-link" href="{% url 'Connectify:about_us' %}"><b>ABOUT US</b></a>
                    <a href="{% url 'Connectify:category' %}" class="nav-link"><b>CATEGORIES</b></a>
                    
                </div>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="contact text-center">
                    <h3><b>CONTACT US</b></h3>
                    <b><img src="https://i.pinimg.com/originals/84/4e/8c/844e8cd4ab26c82286238471f0e5a901.png" width="30px" height="30px"> PHONE NUMBER: +256773820218</b><br>
                    <b><img src="https://cdn4.iconfinder.com/data/icons/social-media-logos-6/512/112-gmail_email_mail-512.png" width="30px" height="30px"> EMAIL: connectifybusinessplatform@gmail.com</b><br>
                    <b><img src="https://pngimg.com/d/facebook_logos_PNG19750.png" width="30px" height="30px"> connectify</b><br>
                    <b><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Instagram_icon.png/2048px-Instagram_icon.png" width="30px" height="30px"> connectify</b><br>
                    <b><img src="https://www.edigitalagency.com.au/wp-content/uploads/new-Twitter-logo-x-black-png.png" width="30px" height="30px"> @connectify</b><br>
                    <b><img src="https://static.vecteezy.com/system/resources/previews/018/930/463/original/tiktok-logo-tikok-icon-transparent-tikok-app-logo-free-png.png" width="30px" height="30px"> @connectify</b><br>
                    <b><img src="https://png.pngtree.com/png-clipart/20221019/original/pngtree-whatsapp-icon-png-image_8704827.png" width="30px" height="30px"> +256704499826</b>
                </div>
            </div>
        </div>
    </div>
</footer>
</html>

Registerbusiness/templates/Registerbusiness/dashboard.html
<!-- dashboard.html -->





{% block content %}
{% load static %}
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome for icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'Connectify/style.css' %}">
    <style>
        /* Additional CSS for responsiveness */
        @media (max-width: 768px) {
            .sidenav {
                width: 100%;
                position: relative;
            }
            .main {
                margin-left: 0;
            }
        }
    </style>
</head>
<body>
    <!-- Side Panel Navigation -->
    <div class="sidenav">
        <a href="#">HOME</a>
        <a href="{% url 'Connectify:about_us' %}">ABOUT US</a>
        <a href="{% url 'Connectify:category' %}">VIEW CATEGORIES</a>
        {% if user.is_authenticated %}
            <a href="{% url 'Connectify:logout' %}">LOGOUT</a>
        {% else %}
            <a href="{% url 'Registerbusiness:business_owner_login' %}?next=/business/manage/">LOGIN</a>
        {% endif %}
        <a href="{% url 'Registerbusiness:add_product' %}">ADD PRODUCT</a>
    </div>
    
    <!-- Page Content -->
    <div class="main">
        <!-- Header -->
        <header class="bg-success py-4" style="background-color: #007B46;">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-1 fw-bolder" style="font-size: 3rem;">Welcome to</h1>
                    <h1 class="display-1 fw-bolder" style="font-size: 3rem;">your Dashboard</h1>
                    <p class="lead fw-normal text-white-50 mb-0" style="font-size: 1.5rem;">Where all your shopping dreams are fulfilled</p>
                </div>
            </div>
        </header>
        
        <!-- Main Content -->
        <main class="container mt-4">
            <!-- Account Information Card -->
            <div class="card mb-4">
                <div class="card-header bg-info text-white">
                    Account Information
                </div>
                <div class="card-body">
                    <p>Name: {{ user.username }}</p>
                    <p>Email: {{ user.email }}</p>
                    <p>Phone: {{ user.phone }}</p>
                </div>
            </div>
            
            <!-- Statistics Card -->
            <div class="card mb-4">
                <div class="card-header bg-info text-white">
                    Statistics
                </div>
                <div class="card-body">
                    <p>Total Sales: UGX{{ total_sales }}</p>
                    <p>Number of Orders: {{ num_orders }}</p>
                    <p>Top Selling Products:</p>
                    <ul>
                        {% for product in top_selling_products %}
                            <li>{{ product.name }} - {{ product.units_sold }} units</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            
            <!-- Recent Orders Card -->
            <div class="card mb-4">
                <div class="card-header bg-info text-white">
                    Recent Orders
                </div>
                <div class="card-body">
                    <ul>
                        {% for order in recent_orders %}
                            <li>Order #{{ order.order_number }} - {{ order.product.name }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </main>
    </div>
 </body> 
 <script>
    // Array of background image URLs
    var backgroundImageUrls = [
        "https://img.freepik.com/premium-photo/shopping-bags-brown-background_934652-2196.jpg",
        "https://as2.ftcdn.net/v2/jpg/03/12/43/13/1000_F_312431352_FCkZ5r0gRzUcS7GyvsRtnxECfXv6EKsJ.jpg",
        "https://png.pngtree.com/background/20230819/original/pngtree-eco-friendly-brown-shopping-bags-with-leaf-shadow-on-green-background-picture-image_4735897.jpg"
        // Add more image URLs as needed
    ];

    var currentImageIndex = 0; // Index of the currently displayed image

    // Function to change the background image
    function changeBackgroundImage() {
        // Increment the current image index
        currentImageIndex = (currentImageIndex + 1) % backgroundImageUrls.length;

        // Get the body element
        var body = document.body;

        // Change the background image
        body.style.backgroundImage = "url('" + backgroundImageUrls[currentImageIndex] + "')";

        // Call the function recursively after a certain interval (e.g., every 10 seconds)
        setTimeout(changeBackgroundImage, 10000); // Change image every 10 seconds (10000 milliseconds)
    }

    // Call the changeBackgroundImage function to start changing the background
    changeBackgroundImage();
</script>     
<footer class="py-5 bg-success" style="background-color: #033d24;">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-6 col-sm-12 mb-4 mb-lg-0">
                <div class="hours">
                    <h3><b>OFFICE HOURS</b></h3>
                    <pre class="try">   
                        <b>MONDAY: 7am-11pm</b>
                        <b>TUESDAY: 7am-11pm</b>
                        <b>WEDNESDAY: 7am-11pm</b>
                        <b>THURSDAY: 7am-11pm</b>
                        <b>FRIDAY: 7am-11pm</b>
                        <b>SATURDAY: 7am-8pm</b>
                        <b>SUNDAY: 7am-7pm</b>
                    </pre>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 mb-4 mb-lg-0">
                <div class="location">
                    <h3><b>LOCATION</b></h3>
                    <pre class="try">
                        <b>KAMPALA UGANDA</b>
                        <b>BUILDING: HAM TOWERS</b>
                        <b>ROOM NUMBER: R45</b>
                        <b>MAKERERE HILL ROAD, KAMPALA</b>
                    </pre>
                </div>
            </div>
            <div class="col-lg-4 col-md-12 col-sm-12 mb-4 mb-lg-0">
                <div class="menu">
                    <h3><b>MENU</b></h3>
                    <a class="nav-link active" aria-current="page" href="{% url 'Connectify:index' %}"><b>HOME</b></a>
                    <a class="nav-link" href="{% url 'Connectify:logout' %}"><b>LOGOUT</b></a>
                    <a class="nav-link" href="{% url 'Connectify:login' %}"><b>LOGIN</b></a>
                    <a class="nav-link" href="{% url 'Connectify:register' %}"><b>SIGNUP</b></a>
                    <a class="nav-link" href="{% url 'Connectify:about_us' %}"><b>ABOUT US</b></a>
                    <a href="{% url 'Connectify:category' %}" class="nav-link"><b>CATEGORIES</b></a>
                    
                </div>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="contact text-center">
                    <h3><b>CONTACT US</b></h3>
                    <b><img src="https://i.pinimg.com/originals/84/4e/8c/844e8cd4ab26c82286238471f0e5a901.png" width="30px" height="30px"> PHONE NUMBER: +256773820218</b><br>
                    <b><img src="https://cdn4.iconfinder.com/data/icons/social-media-logos-6/512/112-gmail_email_mail-512.png" width="30px" height="30px"> EMAIL: connectifybusinessplatform@gmail.com</b><br>
                    <b><img src="https://pngimg.com/d/facebook_logos_PNG19750.png" width="30px" height="30px"> connectify</b><br>
                    <b><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Instagram_icon.png/2048px-Instagram_icon.png" width="30px" height="30px"> connectify</b><br>
                    <b><img src="https://www.edigitalagency.com.au/wp-content/uploads/new-Twitter-logo-x-black-png.png" width="30px" height="30px"> @connectify</b><br>
                    <b><img src="https://static.vecteezy.com/system/resources/previews/018/930/463/original/tiktok-logo-tikok-icon-transparent-tikok-app-logo-free-png.png" width="30px" height="30px"> @connectify</b><br>
                    <b><img src="https://png.pngtree.com/png-clipart/20221019/original/pngtree-whatsapp-icon-png-image_8704827.png" width="30px" height="30px"> +256704499826</b>
                </div>
            </div>
        </div>
    </div>
  </footer>
  </html>
  {% endblock content %}
  
  
      
        

Registerbusiness/templates/Registerbusiness/logout.html
<!-- logout.html -->



{% block title %}Logout{% endblock %}

{% block content %}
    <h1>Logout</h1>
    <p>You have been logged out successfully.</p>
    <p>Click <a href="{% url 'Connectify:index' %}">here</a> to return to the home page.</p>
{% endblock %}