Connectify/urls.py
"""Defines URL patterns for Connectify."""
from django.urls import path, include
from .import views



app_name = 'Connectify'
urlpatterns = [   

    
    path('', views.index, name='index'), #home page
    path('category/', views.categories, name='category'), 
    path('category/<int:category_id>/', views.category_products, name='category_products'),
    path('<int:id>/',views.detail,name='detail'),#show  detail of a single product
    
    path('', include('django.contrib.auth.urls')),
    path('user_logout/',views.user_logout,name= "logout"),
    path('register/', views.register_user, name='register'),
    path('login/', views.login_user, name='login'),
    path('about/', views.about_us, name='about_us'),  # URL for the about us page
   
    
    path('checkout/', views.checkout, name='checkout'),
    path('payments/', views.payment_process, name='payment_process'),
    path('payments/success/', views.payment_success, name='payment_success'),
    
    
   # path('addresses/<int:address_id>/delete/', views.address_delete, name='address_delete'),
    path('cart_summary/', views.cart_summary, name='cart_summary'),
    path('view_businesses/<int:product_id>/', views.view_businesses, name='view_businesses'),
   

    ]

Group1/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings




urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('Connectify.urls', namespace='Connectify')), 
    path('Registerbusiness/', include('Registerbusiness.urls', namespace='Registerbusiness')),  
    path('api/',include('api.urls'))
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    

Registerbusiness/urls.py
from django.urls import path
from . import views

app_name = 'Registerbusiness'
urlpatterns = [

    path('', views.dashboard, name='dashboard'),
    path('register/', views.register_business, name='register_business'),
    path('user_logout/',views.user_logout,name= "logout"),
    path('login/', views.business_owner_login, name='business_owner_login'),
    path('products/add/', views.add_product, name='add_product'),
    path('business_home/',views.business_home, name = 'business_home'),
   
]

api/urls.py
from django.urls import path, include
from. import views
from rest_framework.routers import DefaultRouter

router = DefaultRouter()

router.register("products", views.ProductsViewSet)
router.register("categories", views.CategoriesViewSet)

urlpatterns = [
    path("", include(router.urls)),
    # path('products',views.api_products),
    # path('products',views.ApiProducts.as_view()),
    # path('categories',views.ApiCategories.as_view()),
    # path('product/<str:pk>',views.ApiProduct.as_view()),
    # path('category/<str:pk>',views.ApiCategory.as_view()),
]

Connectify/models.py
from django.db import models
from django.contrib.auth.models import User






class Category(models.Model):
    name = models.CharField(max_length=50)
    image_url = models.CharField(max_length=2083, blank=True)

    def __str__(self):
        return self.name

RATING_CHOICES = (
    (1, '1 star'),
    (2, '2 stars'),
    (3, '3 stars'),
    (4, '4 stars'),
    (5, '5 stars'),
)

class Review(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name="reviews",null=True)
    product=models.ForeignKey("Product",on_delete=models.CASCADE,related_name="reviews",null=True)
    date_created=models.DateTimeField(auto_now_add=True)
    review=models.TextField(max_length=250)
    rating=models.IntegerField(choices=RATING_CHOICES, default=None)

    class Meta:
        verbose_name_plural="Reviews"
    

    def __str__(self):
        return self.product.title
    def get_rating(self):
        return self.rating
    
    
class Product(models.Model):
    title = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='connectify_products')
    price = models.FloatField()
    discount_price = models.FloatField(null=True)
    description = models.TextField()
    image = models.CharField(max_length=2083,null=True)
    
    
    def __str__(self):
        return self.title





class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=10)
    email = models.EmailField(max_length=100)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'
    
    


class Payment(models.Model):
    products = models.ManyToManyField(Product, through='CartItem')
    payment_method = models.CharField(max_length=50)
    amount_paid = models.FloatField()
    payment_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, default='pending')


    
class Cart(models.Model):
    customer = models.OneToOneField(User, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through='CartItem')

    def __str__(self):
        return f"Cart for {self.customer.username}"

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    payment = models.ForeignKey(Payment, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.quantity} x {self.product.title} in Cart for {self.cart.customer.username}"

Connectify/forms.py
import stripe
from django import forms
from django.contrib.auth.models import User
from .models import Product,Customer, Payment
from django.contrib.auth.forms import UserCreationForm
from stripe import Review
from Connectify.models import Review

class ReviewForm(forms.ModelForm):
    review=forms.CharField(widget=forms.Textarea(attrs={'placeholder':"write review"}))
    class Meta:
        model=Review
        fields=['review','rating']


class SignUpForm(UserCreationForm):
    email = forms.EmailField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Email Address'}))
    first_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'First Name'}))
    last_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Name'}))
    phone = forms.CharField(label="", max_length=10, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Phone Number'}))  # Add this line

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'phone')  # Include 'phone' field in fields attribute

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'User Name'
        self.fields['username'].label = ''
        self.fields['username'].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'
class ProductForm(forms.ModelForm):
			class Meta:
				model=Product
				fields=['title','category','price','discount_price','description','image']




class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ['products', 'payment_method', 'amount_paid', 'status']


class CartItemForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, initial=1)

Connectify/views.py
from django.shortcuts import render,redirect, get_object_or_404 
from .models import Product,Category,Customer, Payment, Cart,CartItem,Review
from django.core.paginator import Paginator

from django.contrib.auth import authenticate,login,logout

from django.contrib import messages

from .forms import SignUpForm,ProductForm,  PaymentForm,ReviewForm
from django.contrib.auth.decorators import login_required
from Registerbusiness.models import BusinessOwner

def review(request,id):
    product=Product.objects.get(pk=id)
    user=request.user



def index(request):
  product_objects=Product.objects.all()
  #search code
  item_name=request.GET.get('item_name')
  if  item_name!=''and item_name is not None:
    product_objects=product_objects.filter(title__icontains=item_name)

  #paginator code
  paginator=Paginator(product_objects,20)
  page = request.GET.get('page')
  product_objects=paginator.get_page(page)
    
  return render(request,'Connectify/index.html',{'product_objects':product_objects})

def categories(request):
  categories = Category.objects.all()
  context = {
    "categories": categories
  }
  return render(request,'Connectify/category.html', context)

def category_products(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    products = Product.objects.filter(category_id=category_id)
    context = {
        'category': category,
        'products': products,
    }
    return render(request, 'Connectify/category_products.html', context)
#detail view code
def detail(request, id):
    product_object = Product.objects.get(id=id)
    
    # Calculate discount percentage if discount price is available
    if product_object.discount_price:
        original_price = product_object.price
        discount_price = product_object.discount_price
        discount_percentage = ((original_price - discount_price) / original_price) * 100
    else:
        discount_percentage = None
    
    #getting all reviews
    reviews= Review.objects.filter(product=product_object)
    if request.method == 'POST':
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            new_review = review_form.save(commit=False)
            new_review.product = product_object
            new_review.save()
            return redirect('Connectify:detail', id=id)
    else:
        review_form = ReviewForm()
    #product review form
    review_form=ReviewForm()

    context = {
        'reviews':reviews,
        'review_form': review_form,
        'product_object': product_object,
        'discount_percentage': discount_percentage,
    }

    return render(request, 'Connectify/detail.html', context)
def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # Redirect to the desired page after login
            return redirect('Connectify:index')  # Replace 'dashboard' with your actual landing page URL name
        else:
            # Handle invalid login credentials
            return render(request, 'Connectify/login.html', {'error_message': 'Invalid login'})
    else:
        return render(request, 'Connectify/login.html')
#logout view
def user_logout(request):
  logout(request)
  #redirect to the default home page
  return redirect('Connectify:index')

def register_user(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            customer = Customer.objects.create(
                user=user,
                first_name=form.cleaned_data['first_name'],
                last_name=form.cleaned_data['last_name'],
                email=form.cleaned_data['email'],
                phone=request.POST['phone']  # Assuming 'phone' is in your form
            )
            user = authenticate(username=user.username, password=request.POST['password1'])
            login(request, user)
            messages.success(request, "You have registered your account successfully!")
            return redirect('Connectify:index')  # Redirect to your desired URL after successful registration
    else:
        form = SignUpForm()
    return render(request, 'Connectify/register.html', {'form': form})

def about_us(request):
    # Logic for rendering the about us page
    return render(request, 'Connectify/about_us.html')  # Render the about_us.html template



# Cart Views (Optional)


@login_required
def checkout(request):
    try:
        customer = request.user
        cart = Cart.objects.get(customer=customer)
    except Cart.DoesNotExist:
        # Handle the case where the cart does not exist for the user
        # You can create a new cart here if needed
        # For simplicity, I'll render an empty cart for now
        cart = None

    return render(request, 'Connectify/checkout.html', {'cart': cart})
# Payment Views
def payment_process(request):
    # Implement payment processing logic here
    return render(request, 'Connectify/payment_process.html')

def payment_success(request):
    # Display payment success message or details
    return render(request, 'Connectify/payment_success.html')

# Address Views



def cart_summary(request):
    # get the cart
    cart = Cart(request)
    cart_products = cart.get_prods
    quantities = cart.get_quants
    totals = cart.cart_total()
    
    print("Cart Products:", cart_products)  # Debugging print statement
    
    return render(request, "Connectify/cart_view.html", {"cart_products": cart_products, "quantities": quantities, "totals": totals})



def view_businesses(request, product_id):
   # Retrieve the product object
    product = get_object_or_404(Product, pk=product_id)
    # Get the category of the product
    category = product.category
    # Retrieve businesses that have products within the same category
    businesses = BusinessOwner.objects.filter(business_products__category=category).distinct()
    return render(request, 'Connectify/view_businesses.html', {'businesses': businesses})

Connectify/templates/Connectify/about_us.html
{% extends 'Connectify/base.html' %}

{% block content %}

<br><br><br><br><br>
<body>
    <div class="container">
        <div class="about">
            <header class="header">
                <h2>About Connectify Ecommerce Business Platform</h2>
            </header>

            <div class="section">
                <h2>Who We Are</h2>
                <p>We are Connectify Ecommerce, a platform that helps businesses sell their products online. Think of us as a digital store where you can set up your own shop and reach customers all over the world.</p>
            </div>

            <div class="section">
                <h2>What We Do</h2>
                <p>We make it easy for businesses to have their own online store. You can customize how your store looks, accept payments from customers, manage your inventory, and even ship orders to your customers.</p>
            </div>

            <div class="section">
                <h2>Our Story</h2>
                <p>We started Connectify Ecommerce to make it simple for businesses, big and small, to sell online. Since February 2024, we've been helping businesses grow and reach more customers by providing tools and support for their online stores.</p>
            </div>

            <div class="section">
                <h2>Why Choose Us</h2>
                <ul>
                    <li><strong>Easy to use:</strong> Our platform is designed to be user-friendly, so you don't need to be a tech expert to sell online.</li>
                    <li><strong>Help when you need it:</strong> Our team is here to assist you every step of the way, from setting up your store to growing your sales.</li>
                    <li><strong>Reach a bigger audience:</strong> With an online store, you can sell to people anywhere, not just in your local area.</li>
                    <li><strong>Secure and reliable:</strong> We ensure that your store is safe and that transactions are secure for you and your customers.</li>
                </ul>
            </div>

            <div class="section">
                <h2>JOIN US</h2>
                <p>Whether you're just starting or looking to expand your business online, Connectify Ecommerce is here to help. Start selling online and connect with customers in a whole new way!</p>
            </div>
        </div>
    </div>
</body>
<br><br>
{% endblock %}

Connectify/templates/Connectify/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
   
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="nav-cont">
        <div class="logo"><a class="navbar-brand" href="#"><img src ="{% static 'Connectify/images/images/logo.png' %}" width="100%" height="10%"></a>
        </div>

        <div class="menu-btn">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'Connectify:index' %}"><b>HOME</b></a>
                    </li>
                    
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Connectify:logout' %}"><b>LOGOUT</b></a>
                    </li>
                        
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Connectify:login' %}"><b>LOGIN</b></a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Connectify:register' %}"><b>SIGNUP</b></a>
                    </li>
                           
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Connectify:about_us' %}"><b>ABOUT US</b></a>
                    </li>
                    <li>
                        <a href="{% url 'Connectify:category' %}" class="nav-link"><b>CATEGORIES</b></a>
                    </li>
            </ul>    
        </div>

        <div class="cart-btn">
            <button id="cart" type="button" class="btn-secondary" data-html="true" data-container="body" data-toggle="popover" data-placement="bottom" data-content="">
                cart(0)
            </button>
        </div>
    </div>
</nav>


<head>
    <meta charset="UTF-8">`
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
     
    <script
    src="https://code.jquery.com/jquery-3.7.1.js"
    integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4="
    crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'Connectify/style.css' %}">
    <link rel="stylesheet" href="{% static 'imageslider.css' %}">
    
    <title>CONNECTIFY</title>
</head>

{% block content %}{% endblock content %}
<script>
    // Array of background image URLs
    var backgroundImageUrls = [
        "https://img.freepik.com/premium-photo/shopping-bags-brown-background_934652-2196.jpg",
        "https://img.freepik.com/premium-photo/brown-leather-shopping-bag-brown-background_921026-12318.jpg",
        "https://png.pngtree.com/background/20230819/original/pngtree-eco-friendly-brown-shopping-bags-with-leaf-shadow-on-green-background-picture-image_4735897.jpg",
      
        "https://png.pngtree.com/thumb_back/fw800/background/20231004/pngtree-vibrant-3d-illustration-of-a-red-shopping-bag-on-a-red-image_13541544.png",
        // Add more image URLs as needed
    ];

    var currentImageIndex = 0; // Index of the currently displayed image

    // Function to change the background image
    function changeBackgroundImage() {
        // Increment the current image index
        currentImageIndex = (currentImageIndex + 1) % backgroundImageUrls.length;

        // Get the body element
        var body = document.body;

        // Change the background image
        body.style.backgroundImage = "url('" + backgroundImageUrls[currentImageIndex] + "')";

        // Call the function recursively after a certain interval (e.g., every 10 seconds)
        setTimeout(changeBackgroundImage, 2500); // Change image every 10 seconds (10000 milliseconds)
    }

    // Call the changeBackgroundImage function to start changing the background
    changeBackgroundImage();
</script><hr>

<footer class="py-5 bg-failure" style="background-color: #56cb0e;">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-12 mb-4 mb-lg-0">
                <div class="location">
                    <h3><b>LOCATION</b></h3>
                    <p><b>KAMPALA UGANDA</b></p>
                    <p><b>BUILDING: HAM TOWERS, ROOM R45</b></p>
                    <p><b>MAKERERE HILL ROAD, KAMPALA</b></p>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-12 mb-4 mb-lg-0">
                <div class="menu">
                    <h3><b>MENU</b></h3>
                    <a class="nav-link active" aria-current="page" href="{% url 'Connectify:index' %}"><b>HOME</b></a>
                    <a class="nav-link" href="{% url 'Connectify:logout' %}"><b>LOGOUT</b></a>
                    <a class="nav-link" href="{% url 'Connectify:login' %}"><b>LOGIN</b></a>
                    <a class="nav-link" href="{% url 'Connectify:register' %}"><b>SIGNUP</b></a>
                    <a class="nav-link" href="{% url 'Connectify:about_us' %}"><b>ABOUT US</b></a>
                    <a href="{% url 'Connectify:category' %}" class="nav-link"><b>CATEGORIES</b></a>
                    <a href="{% url 'Registerbusiness:business_home' %}" class="nav-link"><b>REGISTER YOUR BUSINESS</b></a>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-12">
                <div class="row">
                    <div class="col-md-12 mb-4 mb-lg-0">
                        <div class="contact text-center">
                            <h3><b>CONTACT US</b></h3>
                            <p><b><img src="https://i.pinimg.com/originals/84/4e/8c/844e8cd4ab26c82286238471f0e5a901.png" width="30px" height="30px"> +256772022047</b></p>
                            <p><b><img src="https://cdn4.iconfinder.com/data/icons/social-media-logos-6/512/112-gmail_email_mail-512.png" width="30px" height="30px"> connectifybusinessplatform@gmail.com</b></p>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="social-media text-center">
                            <b><img src="https://pngimg.com/d/facebook_logos_PNG19750.png" width="30px" height="30px">@Connectify</b>
                            <b><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Instagram_icon.png/2048px-Instagram_icon.png" width="30px" height="30px">@Connectify</b>
                            <b><img src="https://www.edigitalagency.com.au/wp-content/uploads/new-Twitter-logo-x-black-png.png" width="30px" height="30px">@Connectify</b>
                            <b><img src="https://static.vecteezy.com/system/resources/previews/018/930/463/original/tiktok-logo-tikok-icon-transparent-tikok-app-logo-free-png.png" width="30px" height="30px"> @Connectify</b>
                            <b><img src="https://png.pngtree.com/png-clipart/20221019/original/pngtree-whatsapp-icon-png-image_8704827.png" width="30px" height="30px">0772022047</b>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
</html>

Connectify/templates/Connectify/category.html
{% extends 'Connectify/base.html' %}
{% block content %}
<br><br><br><br><br><br>
<body>
    <div class="container">
        <h1>Categories</h1>
        <div class="row">
            {% for category in categories %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <img src="{{ category.image_url }}" class="card-img-top" alt="{{ category.name }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ category.name }}</h5>
                            <a href="{% url 'Connectify:category_products' category.id %}" class="btn btn-primary">View Products</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>
{% endblock %}

Connectify/templates/Connectify/payment_process.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Payment Processing</title>
</head>
<body>
    <h1>Payment Processing</h1>
    <!-- Display payment processing message or form -->
    <p>Your payment is being processed. Please wait...</p>
</body>
</html>

Connectify/templates/Connectify/payment_sucess.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Payment Success</title>
</head>
<body>
    <h1>Payment Success</h1>
    <p>Your payment was successful!</p>
    <!-- Display payment details or a thank you message -->
</body>
</html>

Connectify/templates/Connectify/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'Connectify/style.css' %}">
    <title>Document</title>
</head>
<body>
    <div class="signup">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <br></br>
                <form method="POST" action="{% url 'Connectify:register' %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <br></br>
           
           <button type="submit" class="Sign">Sign Up</button>
                </form>
                <br></br>
                <br></br>
            </div>
        </div>
    </div>
</body>
<script>
    // Array of background image URLs
    var backgroundImageUrls = [
        "https://img.freepik.com/premium-photo/shopping-bags-brown-background_934652-2196.jpg",
        "https://img.freepik.com/premium-photo/brown-leather-shopping-bag-brown-background_921026-12318.jpg",
        "https://png.pngtree.com/background/20230819/original/pngtree-eco-friendly-brown-shopping-bags-with-leaf-shadow-on-green-background-picture-image_4735897.jpg",
        "https://previews.123rf.com/images/kurhan/kurhan1510/kurhan151001204/46515714-grocery-shopping-cart-with-vegetables-over-green-background.jpg",
        "https://png.pngtree.com/thumb_back/fw800/background/20231004/pngtree-vibrant-3d-illustration-of-a-red-shopping-bag-on-a-red-image_13541544.png",
        // Add more image URLs as needed
    ];

    var currentImageIndex = 0; // Index of the currently displayed image

    // Function to change the background image
    function changeBackgroundImage() {
        // Increment the current image index
        currentImageIndex = (currentImageIndex + 1) % backgroundImageUrls.length;

        // Get the body element
        var body = document.body;

        // Change the background image
        body.style.backgroundImage = "url('" + backgroundImageUrls[currentImageIndex] + "')";

        // Call the function recursively after a certain interval (e.g., every 10 seconds)
        setTimeout(changeBackgroundImage, 2500); // Change image every 10 seconds (10000 milliseconds)
    }

    // Call the changeBackgroundImage function to start changing the background
    changeBackgroundImage();
</script><hr>
<footer class="py-5 bg-success" style="background-color: #033d24;">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-12 mb-4 mb-lg-0">
                <div class="location">
                    <h3><b>LOCATION</b></h3>
                    <p><b>KAMPALA UGANDA</b></p>
                    <p><b>BUILDING: HAM TOWERS, ROOM R45</b></p>
                    <p><b>MAKERERE HILL ROAD, KAMPALA</b></p>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-12 mb-4 mb-lg-0">
                <div class="menu">
                    <h3><b>MENU</b></h3>
                    <a class="nav-link active" aria-current="page" href="{% url 'Connectify:index' %}"><b>HOME</b></a>
                    <a class="nav-link" href="{% url 'Connectify:logout' %}"><b>LOGOUT</b></a>
                    <a class="nav-link" href="{% url 'Connectify:login' %}"><b>LOGIN</b></a>
                    <a class="nav-link" href="{% url 'Connectify:register' %}"><b>SIGNUP</b></a>
                    <a class="nav-link" href="{% url 'Connectify:about_us' %}"><b>ABOUT US</b></a>
                    <a href="{% url 'Connectify:category' %}" class="nav-link"><b>CATEGORIES</b></a>
                    <a href="{% url 'Registerbusiness:business_home' %}" class="nav-link"><b>REGISTER YOUR BUSINESS</b></a>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-12">
                <div class="row">
                    <div class="col-md-12 mb-4 mb-lg-0">
                        <div class="contact text-center">
                            <h3><b>CONTACT US</b></h3>
                            <p><b><img src="https://i.pinimg.com/originals/84/4e/8c/844e8cd4ab26c82286238471f0e5a901.png" width="30px" height="30px"> +256772022047</b></p>
                            <p><b><img src="https://cdn4.iconfinder.com/data/icons/social-media-logos-6/512/112-gmail_email_mail-512.png" width="30px" height="30px"> connectifybusinessplatform@gmail.com</b></p>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="social-media text-center">
                            <b><img src="https://pngimg.com/d/facebook_logos_PNG19750.png" width="30px" height="30px">@Connectify</b>
                            <b><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Instagram_icon.png/2048px-Instagram_icon.png" width="30px" height="30px">@Connectify</b>
                            <b><img src="https://www.edigitalagency.com.au/wp-content/uploads/new-Twitter-logo-x-black-png.png" width="30px" height="30px">@Connectify</b>
                            <b><img src="https://static.vecteezy.com/system/resources/previews/018/930/463/original/tiktok-logo-tikok-icon-transparent-tikok-app-logo-free-png.png" width="30px" height="30px"> @Connectify</b>
                            <b><img src="https://png.pngtree.com/png-clipart/20221019/original/pngtree-whatsapp-icon-png-image_8704827.png" width="30px" height="30px">0772022047</b>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

</html>